@startuml DSS
skinparam style strictuml
skinparam defaultfontname Verdana
skinparam sequence {
    MessageAlign center
}
hide empty members
title DSS CU01b - Récupérer cours

actor ":Enseignant" as e
participant ":Systeme" as s

e -> s : getCoursUtilisateur(token : string)
e <<-- s : liste des cours de l'enseignant utilisateur
note left : dans UI : selectionne le cours\net affiche son détail et sa liste d'étudiants
@enduml